# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/LocalLLMRAG',
                'doc_host': 'https://jason-drury.github.io',
                'git_url': 'https://github.com/jason-drury/LocalLLMRAG',
                'lib_path': 'LocalLLMRAG'},
  'syms': {'LocalLLMRAG.core': {'LocalLLMRAG.core.foo': ('core.html#foo', 'LocalLLMRAG/core.py')}}}
